SELECT 
	A.POKEMON_NAME AS POKEMON_NAME,
	A.STR * B.MULTIPLIER AS modifiedStrength,
	B.ELEMENT AS ELEMENT
FROM
	POKEMON  AS A
LEFT JOIN
	MULTIPLIERS  AS B
ON 
	A.ELEMENT_ID = B.ID
WHERE
	A.STR * B.MULTIPLIER >= 40
ORDER BY
	A.STR * B.MULTIPLIER DESC